### ISSUE TITLE
Package OpenCL was not found

### ISSUE THREAD

**Issue by LeMoussel** [jgillich/go-opencl#4]
When I do `go get github.com/jgillich/go-opencl/cl`, I got this error

> Package OpenCL was not found in the pkg-config search path.
> Perhaps you should add the directory containing `OpenCL.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'OpenCL' found
> pkg-config: exit status 1

On my system with NVIDIA driver, OpenCL exist in `/usr/lib/x86_64-linux-gnu`

> dev@dev-Veriton-M421G:~/go/src/gobismuth$ ls -l /usr/lib/x86_64-linux-gnu/libOpenCL*
> lrwxrwxrwx 1 root root    14 oct.   4 15:15 /usr/lib/x86_64-linux-gnu/libOpenCL.so -> libOpenCL.so.1
> lrwxrwxrwx 1 root root    18 avril  5  2017 /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 -> libOpenCL.so.1.0.0
> -rw-r--r-- 1 root root 43072 avril  5  2017 /usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0

**Comment by LeMoussel** [comment]
In `/usr/lib/pkgconfig`, I create `OpenCL.pc` file with this in

> prefix=/usr
> exec_prefix=${prefix}
> libdir=${prefix}/lib/x86_64-linux-gnu
> 
> Name: OpenCL
> Description: OpenCL
> Libs: -L${libdir} -lOpenCL
> Version: 1.0.0

**Comment by jgillich** [comment]
What distribution are you on?

**Comment by LeMoussel** [comment]
Ubuntu with Nvidia SDK.

**Comment by jgillich** [comment]
Ok, so Nvidia does not ship a pkg-config file, lovely. Other ICDs like the one from Intel install to custom locations, so we need to use pkg-config. Manually creating the pkg-config file like you did is the only solution I can think of.
