### ISSUE TITLE
Null character in plateform information string

### ISSUE THREAD

**Issue by LeMoussel** [jgillich/go-opencl#5]
In plateform information string, there is null character, '\0' at the end.

In `plateform.go`, `getInfoString(...)` return string() from  C string.
Like `getInfoString(...)` from `device.go`, it should be :

> 	return C.GoStringN((*C.char)(unsafe.Pointer(&strC)), C.int(strN)), nil

**Comment by LeMoussel** [comment]
I tested, I tested but I still have null character, '\0' at the end.
It's OK with 
`	return C.GoString((*C.char)(unsafe.Pointer(&strC))), nil
`
au lieu de  ``

**Comment by jgillich** [comment]
Hm..on another function, [the docs say](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetProgramInfo.html):

>  The actual number of characters that represents the program source code including the null terminator is returned in param_value_size_ret. 

Not sure why null terminated strings require a length, but it's probably safe to assume strings won't contain a null elsewhere.
