### ISSUE TITLE
missing func() to get Plateform & Device id.

### ISSUE THREAD

**Issue by LeMoussel** [jgillich/go-opencl#6]
`Platform.id` & `Device.id` are not exported.
It would be interesting to have a function to obtain these values. eg `func (p *Platform) GetID()` ?

**Comment by jgillich** [comment]
They are abstract types and only used in OpenCL calls. Perhaps you mean index?

**Comment by LeMoussel** [comment]
To get specific information with `C.clGetDeviceInfo`
for example on specific AMD GPU device, if deviceName == "Ellesmere, I got devicename with OpenCL extension like this `getDeviceInfo(deviceID, 0x4038)`
0x4038 =  CL_DEVICE_BOARD_NAME_AMD, Ref: [cl_amd_device_attribute_query](https://www.khronos.org/registry/OpenCL/extensions/amd/cl_amd_device_attribute_query.txt)

**Comment by jgillich** [comment]
Would exporting `(d *Device) getInfo*` help? I think it would be best for cl calls to remain in this package.

**Comment by LeMoussel** [comment]
Yep! I agree with you.
